stages:
  train:
    cmd: python train.py
    deps:
      - data
      - train.py
    params:
      - params.yaml:
    outs:
      - model.pt
      - hist.csv
    metrics:
      - training/metrics.json:
          persist: true
          cache: false
    plots:
      - training/plots:
          persist: true
      - dogs:
          cache: False
